/**
 * Guest mode — playing without an account.
 *
 * Storage: the flag lives in `localStorage`, not `sessionStorage`, so a guest
 * who opens a shared challenge link in a new tab stays a guest instead of being
 * bounced to /login. Earlier builds wrote it to `sessionStorage`, so reads fall
 * back to that and `exitGuestMode()` clears both.
 *
 * Naming: every guest gets a unique display name ("Guest-A7K2"). Two guests in
 * the same multiplayer room would otherwise both be "Guest", which makes the
 * board labels, the chat attribution and the join/leave toasts ambiguous.
 * ws-server also de-duplicates identical names per room as a backstop.
 */

const FLAG_KEY = "wordle:guest";
const NAME_KEY = "wordle:guestName";

/** Guest names generated by `guestName()`. Anything else is treated as stale. */
const GUEST_NAME_PATTERN = /^Guest-[A-Z0-9]{4}$/;

function read(key: string): string | null {
  if (typeof window === "undefined") return null;
  try {
    return window.localStorage.getItem(key) ?? window.sessionStorage.getItem(key);
  } catch {
    return null;
  }
}

function write(key: string, value: string): void {
  if (typeof window === "undefined") return;
  try {
    window.localStorage.setItem(key, value);
  } catch {
    /* private mode / storage disabled — guest mode degrades to this page only */
  }
}

function remove(key: string): void {
  if (typeof window === "undefined") return;
  try { window.localStorage.removeItem(key); } catch {}
  try { window.sessionStorage.removeItem(key); } catch {}
}

function randomSuffix(): string {
  const alphabet = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"; // no I/O/0/1
  const bytes = new Uint8Array(4);
  if (typeof crypto !== "undefined" && crypto.getRandomValues) {
    crypto.getRandomValues(bytes);
  } else {
    for (let i = 0; i < bytes.length; i++) bytes[i] = Math.floor(Math.random() * 256);
  }
  return Array.from(bytes, (b) => alphabet[b % alphabet.length]).join("");
}

/** True when the visitor chose "Continue as guest" and has not signed in since. */
export function isGuest(): boolean {
  return read(FLAG_KEY) === "1";
}

/**
 * This guest's display name, generated once and reused. Call from an effect or
 * an event handler, never during render — it writes to storage on first use.
 */
export function guestName(): string {
  const existing = read(NAME_KEY);
  if (existing && GUEST_NAME_PATTERN.test(existing)) return existing;
  const name = `Guest-${randomSuffix()}`;
  write(NAME_KEY, name);
  return name;
}

/** Enter guest mode and return the display name to use. */
export function enterGuestMode(): string {
  write(FLAG_KEY, "1");
  return guestName();
}

/** Leave guest mode. Safe to call when not a guest. */
export function exitGuestMode(): void {
  remove(FLAG_KEY);
  remove(NAME_KEY);
}
